export const THEM_NGUOI_DUNG = 'THEM_NGUOI_DUNG';
export const XOA_NGUOI_DUNG = 'XOA_NGUOI_DUNG';
export const SUA_NGUOI_DUNG = 'SUA_NGUOI_DUNG';
export const NGUOI_DUNG_CAP_NHAT = 'NGUOI_DUNG_CAP_NHAT';
